version: "3.3"

networks:
  magento2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24

services:
  magento2-nginx:
     build:
       context: .
       dockerfile: docker/nginx/Dockerfile
     image: magento2-nginx
     env_file:
       - ./docker/.docker.env
     container_name: magento2-nginx
     networks:
       - magento2
     ports:
       - 80:80
       - 443:443
     volumes:
       - ./html:/var/www/html
       - ./docker/nginx/sites-available:/etc/nginx/sites-available
     depends_on:
       - magento2-php
     restart: always
  magento2-php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      image: magento2-php
      env_file:
        - ./docker/.docker.env
      container_name: magento2-php
      networks:
        - magento2
      depends_on:
        - magento2-mysql
      volumes:
        - ./html:/var/www/html
        - ./docker/php/php-fpm.ini:/usr/local/etc/php/php.ini
      restart: always
  magento2-mysql:
       image: mysql:5.7
       env_file:
          - ./docker/.docker.env
       container_name: magento2-mysql
       networks:
         - magento
       ports:
         - 3306:3306
       volumes:
         - magento2-mysql:/var/lib/mysql
         - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/mycustom.cnf
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: Magento2Docker
         MYSQL_DATABASE: magento2
         MYSQL_USER: admin
         MYSQL_PASSWORD: Magento2Docker

volumes:
   magento2-mysql:
     driver: "local"